### ISSUE TITLE
Choose external save location

### ISSUE THREAD

**Issue by blopez0909** [Kallys/MediaDownloader#2]
How would i go about setting the download location to my thumb drive which is in /media/HDD/? whenever i do that it creates a folder within the MediaDownloader folder and saves it there instead of my thumb drive.

**Comment by Kallys** [comment]
Hey blopez0909 !

I chose to restrict download location to MediaDownloader sub-folders only since I though it is easy to bypass using file system operations and it's easier to develop. I agree that it's not very user friendly and I plan to refactor configs some day (both how to change them and how they are applied).

Until then, and that's how I use MediaDownloader with an external drive, I would suggest you to create a symbolic link to your device partition. Be sure it is writable for your http server user.

For example, in a terminal :
`ln -s /media/HDD/ <path to MediaDownloader>/downloads/external`
`chgrp www-data /media/HDD`
`chmod g+rw /media/HDD`

And set 'output_folder' to 'downloads/external' in config.php file.
